name: cached_repository
description: Simple, easy to use and extensible cached repository which can store all you need.
version: 0.0.1
homepage: https://github.com/Oliinyk-Artemii/cached_repository

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  rxdart: ^0.27.3
  synchronized: ^3.0.0
  flutter_secure_storage: ^5.0.2
  worker_manager: ^3.2.6
  hive_flutter: ^1.1.0
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0