name: cached_repository
description: Simple, easy to use and extensible cached repository which can store all you need.
version: 0.1.0
homepage: https://github.com/Oliinyk-Artemii/cached_repository

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: 1.1.0
  synchronized: 3.0.1
  rxdart: 0.27.7
  hive_flutter: 1.1.0
  worker_manager: 4.2.6
  flutter_secure_storage: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0