name: cached_repository
description: Simple, easy to use and extensible cached repository which can store all you need.
version: 0.1.2
homepage: https://github.com/Oliinyk-Artemii/cached_repository

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.3.0
  synchronized: ^3.1.0
  rxdart: ^0.27.7
  hive_flutter: ^1.1.0
  worker_manager: ^5.0.3
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0